plugins:
  - serverless-offline

service: testApp

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:667983010119:table/todo-table'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: GET
          path: /
          request:
            parameters:
              paths:
                name: false
      - http:
          method: GET
          path: /{name}
          request:
            parameters:
              paths:
                name: true
  addTodo:
    handler: handler.add
    events:
      - http:
          method: POST
          path: /
  deleteTodo:
    handler: handler.delete
    events:
      - http:
          method: DELETE
          path: /
